version: "3"
services:
  api:
    build: .
    command: npm run start
    volumes:
      - .:/api/
      - /api/node_modules
    ports:
      - 5000:5000
    depends_on:
      - db
      - db_test

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - .env

  db_test:
    image: postgres
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    env_file:
      - .env.test

volumes:
  api:
  postgres_data:
  postgres_data_test:
