version: "3"
services:
  api:
    build: .
    command: npm run start
    volumes:
      - .:/api/
      - /api/node_modules
    ports:
      - 5002:5002
    depends_on:
      - db
      - db_test

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=jobtracker_db
      - POSTGRES_USER=jeevan
      - POSTGRES_PASSWORD=localPassword

  db_test:
    image: postgres
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=jobtracker_db_test
      - POSTGRES_USER=jeevan
      - POSTGRES_PASSWORD=testPassword

volumes:
  api:
  postgres_data:
  postgres_data_test:
