name: backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"

  pull_request:
    branches: [main]
    paths:
      - "backend/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./backend/"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        env:
          DATABASE_URL: postgres://jobtracker:testPassword@localhost:5434/db_test
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          MAP_API_KEY: ${{ secrets.MAP_API_KEY }}
          MAP_URL: ${{ secrets.MAP_URL }}

        uses: actions/setup-node@v2.1.4

      - run: npm ci
      - run: sudo docker-compose up -d db_test
      - run: npm run build --if-present
      - run: |
          export DATABASE_URL="$DATABASE_URL"
          export TOKEN_SECRET="$TOKEN_SECRET"
          export MAP_API_KEY="$MAP_API_KEY"
          export MAP_URL="$MAP_URL"
          echo "$DATABASE_URL"
          npm run test

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: Passed tests, pushing latest changes.
          branch: main

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push backend to dokku
        uses: dokku/github-action@v1.0.1
        with:
          branch: main
          git_remote_url: "ssh://dokku@ente-dokku.jeevan.link/jtr-backend"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: --force
